name: Docker Image CD

#These are the events that this workflow will be triggered for
on:
  push:
    branches: [ DevOps ]
  pull_request:
    branches: [ DevOps ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout our git repository
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    
    # Log in to docker to be able to push to our profile
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: create-json
      # You may pin to the exact commit or the version.
      # uses: jsdaniell/create-json@4a4e510bf85e1193b9fca74074d2bf4ee26de08c
      uses: jsdaniell/create-json@1.1.2
      with:
        # The name of the file to be written. | file.json 
        name: appsettings.json
        # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" 
        json: ${{secrets.APPSETTINGS}}
        # Optional subfolder directory to save the json file. | src/ 
        dir: ./StackLite/WebAPI
    
    # We build our docker image and then push to docker hub
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: ./StackLite
        # Path to the Dockerfile
        file: ./Dockerfile
        tags: index.docker.io/${{secrets.DOCKERHUB_USERNAME}}/stacklite:${{github.sha}}
        push: true
