# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stackliteprep

on:
  push:
    branches:
      - DevOps
  workflow_dispatch:
env:
  WORKING_DIRECTORY: StackLite
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: Production
    steps:
    - uses: actions/checkout@v2

    - name: create-json
      # You may pin to the exact commit or the version.
      # uses: jsdaniell/create-json@4a4e510bf85e1193b9fca74074d2bf4ee26de08c
      uses: jsdaniell/create-json@1.1.2
      with:
        # The name of the file to be written. | file.json 
        name: appsettings.json
        # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" 
        json: ${{ secrets.APPSETTINGS }}
        # Optional subfolder directory to save the json file. | src/ 
        dir: ${{env.WORKING_DIRECTORY}}/WebAPI
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_38e1eecc221d4949b59db1df157c9c98 }}
  
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: ${{env.WORKING_DIRECTORY}}
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}/stacklite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stackliteprep'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_891f420269784dc182143ae3a9458bba }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}/stacklite:${{ github.sha }}'
