# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stackliteprep

on:
  push:
    branches:
      - DevOps
  workflow_dispatch:
env:
  WORKING_DIRECTORY: StackLite
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: Production
    steps:
    - uses: actions/checkout@v2

    - name: Read appsettings
      env:
        APP_SETTINGS: ${{ secrets.APPSETTINGS }}
      run: printf $APP_SETTINGS >> ${{ env.WORKING_DIRECTORY}}/WebAPI/Properties/appsettings.json
      run: cat ${{ env.WORKING_DIRECTORY}}/WebAPI/Properties/appsettings.json

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1

  #   - name: Log in to registry
  #     uses: docker/login-action@v1
  #     with:
  #       registry: https://index.docker.io/v1/
  #       username: ${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}
  #       password: ${{ secrets.AzureAppService_ContainerPassword_38e1eecc221d4949b59db1df157c9c98 }}
  
  #   - name: Build and push container image to registry
  #     uses: docker/build-push-action@v2
  #     with:
  #       push: true
  #       tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}/stacklite:${{ github.sha }}
  #       file: ./Dockerfile

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Deploy to Azure Web App
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'stackliteprep'
  #       slot-name: 'production'
  #       publish-profile: ${{ secrets.AzureAppService_PublishProfile_891f420269784dc182143ae3a9458bba }}
  #       images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85392fc8be85467fa66280fa1bc3a8d6 }}/stacklite:${{ github.sha }}'
